### ISSUE TITLE
add backslashes to jscript output for html validation

### ISSUE THREAD

**Issue by torvista** [mc12345678/zen-colorbox#11]
html validator addon in Firefox points these out.

tpl_modules_main_product_image.php

`document.write('<?php echo '<a href="javascript:popupWindow(\\\'' . zen_href_link(FILENAME_POPUP_IMAGE, 'pID=' . $_GET['products_id']) . '\\\')">' . zen_image(addslashes($products_image_medium), addslashes($products_name), MEDIUM_IMAGE_WIDTH, MEDIUM_IMAGE_HEIGHT) . '<br /><span class="imgLink">' . TEXT_CLICK_TO_ENLARGE . '<\/span><\/a>'; //steve added backslashes for validation ?>');`

zen_colorbox.php

`    $script_link = '<script type="text/javascript"><!--' . "\n" . 'document.write(\'' . ($flag_display_large ? '<a href="' . zen_colorbox($products_image_large, addslashes($products_name), LARGE_IMAGE_WIDTH, LARGE_IMAGE_HEIGHT) . '" rel="' . $rel . '" title="' . addslashes($products_name) . '">' . $thumb_slashes . '<br />' . TEXT_CLICK_TO_ENLARGE . '<\/a>' : $thumb_slashes) . '\');' . "\n" . '//--></script>'; //steve add backslashes for validation`

**Comment by mc12345678** [comment]
> tpl_modules_main_product_image.php
>
>`document.write('<?php echo '<a href="javascript:popupWindow(\\\'' . zen_href_link(FILENAME_POPUP_IMAGE, 'pID=' . $_GET['products_id']) . '\\\')">' . zen_image(addslashes($products_image_medium), addslashes($products_name), MEDIUM_IMAGE_WIDTH, MEDIUM_IMAGE_HEIGHT) . '<br /><span class="imgLink">' . TEXT_CLICK_TO_ENLARGE . '<\/span><\/a>'; //steve added backslashes for validation ?>');`

The code that has been modified to include additional back-slashes is original ZC code and only becomes an issue in this plugin when either the function zen_colorbox is no longer on the server or if zen_colorbox has been disabled in the admin and therefore returns to standard operation.  

This change should be suggested to the ZC site for incorporation.  It doesn't make sense that a plugin should be loaded and disabled in order to "fix" something in the core.

Similarly, `zen_colorbox.php` has code like the first `document.write` which originates from core code and is executed when the plugin is disabled. While in support of making improvements, shouldn't this also be addressed in ZC and not just in this plugin?

BTW, I am not getting any such recommendations from the HTML validation performed by Firefox V52.5.3 nor by the online HTML validator.  At the moment the only comments seen on a ZC 1.5.5 product info page was the use of the type parameter (`type="text/javascript"`) in the script tags.  The page is being rendered using HTML 5, which may also play a factor.

Can make the changes recommended for the Colorbox specific aspects, though no tool is telling me that it is necessary. To make the changes to the default ZC code, then would have to identify that code as a difference to implement, though again tools I'm using don't complain about the above either way.

**Comment by torvista** [comment]
These snippets are those used by the plugin and once the plugin is functioning, those are what are used on the page, not the original ZC code from which they are copied.
So while the same comments can be made about the ZC code, I'm looking at this plugin at the moment, so that's what gets my feedback.
Here is the screenshot of the error report:
![clipboard01](https://user-images.githubusercontent.com/4391026/34957047-2aba77ca-fa2c-11e7-8bff-372b33a8beee.gif)
regards

**Comment by mc12345678** [comment]
Having run a test through the same html validators with the escape applied and not seeing any complaints from them (again) I have prepared changes to incorporate the comment across the board. Will also need to comment that this is a change from the base install so that the modification(s) are properly incorporated. Likely to use the same escape mechanism seen in ZC 1.5.5s includes/templates/template_default/common/header.php.

**Comment by torvista** [comment]
Just using this codeset again and find it still flags as invalid.

**Comment by mc12345678** [comment]
Did I imagine it or was there a message here that perhaps got deleted?

The message related to still seeing a validation issue. I'm not sure if the previous commits had resolved the issue leading to deletion, or if the comment is "buried" somewhere. :)

**Comment by torvista** [comment]
I made the comment then I found it was corrected in the 2.13 branch.
