### ISSUE TITLE
colorbox is not a valid keyword for rel

### ISSUE THREAD

**Issue by torvista** [mc12345678/zen-colorbox#19]
similar to:
https://stackoverflow.com/questions/29082791/bad-value-for-attribute-rel-on-element-a-the-string-is-not-a-registered

**Comment by mc12345678** [comment]
Sorry, could have responded the same day this was  posted, but thought I would get to the resolution faster.  Acknowledging receipt of the comment/issue and had previously considered modifying the `rel=` aspect; however, had not done so.  Will look into what it takes to possibly use a `data-` style parameter so that passes validation.  This may require submitting a pull request to the original code, but whatever it takes, right?

**Comment by torvista** [comment]
> but whatever it takes, right?

I think so, we are in the world of nit-picking are we not?
Anything that prevents this is a nit:
![clipboard01](https://user-images.githubusercontent.com/4391026/51543559-1f283a80-1e5e-11e9-99c0-df071b401ded.gif)

For some reason I cannot comment at the end of this thread.
Yes I think the rel change should be data-colorbox. 
Just changing this in the three files referenced breaks the lightbox: the javascript also requires modification.
I tried briefly, but the required changes are not easily apparent (to me).

**Comment by mc12345678** [comment]
Could you check: https://github.com/mc12345678/zen-colorbox/compare/v2.1.3...mc12345678:v2.1.3-rel-to-data-rel

which is basically a diff from the previously tracked version 2.1.3 that didn't yet get pushed to the Zen Cart site where data-rel is used instead of rel?

I want to merge the changes into a single commit, but at the moment it doesn't seem so easy (easy from my own computer but I'm remotely modifying).

**Comment by mc12345678** [comment]
FYI, I may actually change the use of `data-rel` to `data-colorbox` for improved clarity and a bit of uniqueness on the page in the event some other code is added that chooses to use `data-rel`.

**Comment by mc12345678** [comment]
Fixes #21.

**Comment by mc12345678** [comment]
Fixed in https://github.com/mc12345678/zen-colorbox/commit/0c1573d03ae72900df15ebda5b3944caf5301c39
